plugins:
  discourse_news_enabled:
    default: false
    validator: AllowNewsEnabledValidator
    client: true
  discourse_news_category:
    type: category
    default: ''
    client: true
  discourse_news_icon:
    default: ''
    client: true
