plugins:
  discourse_news_enabled:
    default: false
    validator: AllowNewsEnabledValidator
    client: true
  discourse_news_source:
    default: "category"
    client: true
    type: enum
    choices:
      - category
      - rss
  discourse_news_category:
    type: category_list
    default: ''
    client: true
  discourse_news_rss:
    default: ''
  discourse_news_icon:
    default: ''
    client: true
  discourse_news_excerpt_length:
    default: 10000
  discourse_news_meta:
    default: false
    client: true
  discourse_news_sort:
    type: enum
    default: "bumped_at"
    choices:
      - bumped_at
      - created_at
